### ISSUE TITLE
Setup travis & coverage

### ISSUE THREAD

**Issue by RamyElkest** [RamyElkest/apollo-chat-api#1]
and add to readme

**Comment by recurza** [comment]
Hi, I came from hacktoberfest and would like to work on this

**Comment by RamyElkest** [comment]
Thanks @recurza 
I set up travis and coveralls, however coveralls needs some setting up on the repository side

( we probably need to npm i --save istanbul coveralls ) then follow https://github.com/nickmerwin/node-coveralls#istanbul

That requires setting a .yml.coveralls with a config, there should be a quick tutorial out there

let me if you still want to take it / need some help :+1:

**Comment by recurza** [comment]
Sure I'll try to set it up 😁

**Comment by recurza** [comment]
I'm a bit confused: the coveralls website said Travis users don't need a coveralls.yml. So we are using istanbul instead of travis?

**Comment by RamyElkest** [comment]
You're right @recurza we don't need a yml file :+1: 

So mocha is the testing framework, istanbul is coverage library which determines how much is covered by  the tests, and travis is the continuous integration which runs all these on every pull request.

the tests are currently in api/**/*.test.js (passing this to mocha should have found them)
but (currently) we also have to pass the --compilers argument to mocha (and istanbul) for it to work with es6.

even after this is set up, istanbul reports "no coverage information found", this is probably linked to https://github.com/gotwarlost/istanbul/issues/262, which suggested using babel-istanbul.

Then it worked.. but it wasn't as straight forward as i thought.. so sorry about that ;)

let me know if you have any questions

**Comment by recurza** [comment]
oh I see. Thanks for explaining :)

**Comment by RamyElkest** [comment]
Thank you for looking into it :100:
