### ISSUE TITLE
Setup mongodb (and probably mongoose)

### ISSUE THREAD

**Issue by RamyElkest** [RamyElkest/apollo-chat-api#2]
Currently api/queries/models.js uses mock data

The idea is to create mongodb collections, and define the schemas with mongoose (this should be in a separate file/folder `connectors.js` over an interface (so no db queries directly in models.js)

As far as I can see we only have 3 collections, Users, Threads and Messages.

We'll probably also need a seed file (which will probably just populate the current mock data)

Start with as little or as much as you feel like, I can break this down, post here before starting as to not step over each other;)

Thanks
- [x] Add mongodb and mongoose to `package.json`
- [x] Define mongoose schemas for collections `Users` `Threads` and `Messages` (and any more you can think of)
- [x] Define `mongodb.js` in connectors folder (This is an interface which will be called from the models)
- [x] Write tests in `mongodb.test.js` for `mongodb.js`
- [x] Add `migration/setup` and `seed` file to populate mock data

**Comment by ajzawawi** [comment]
Hey @RamyElkest. I'd like to work on this.

**Comment by SidVader** [comment]
Hi @RamyElkest I am interested in working on it. I have been working on mongodb in recent days and it seems interesting.

**Comment by ajzawawi** [comment]
@RamyElkest submitted a PR for first item on the task list.

**Comment by RamyElkest** [comment]
thanks @ajzawawi!

**Comment by ajzawawi** [comment]
@RamyElkest submitted a PR for second item on the task list. Wasn't sure if you wanted that inside of the API folder.

**Comment by ajzawawi** [comment]
@RamyElkest Can you clarify task #3 so I can work on it?

**Comment by RamyElkest** [comment]
I guess it can be broken into two steps
currently for each model we have the following queries
`Messages`
  `getByThreadId` -> `Messages.find({threadId: threadId})`
  `addMessage` -> `Messages.insert(..)`
`Threads`
  `getById` -> `Threads.findOne(..)`
`Users`
  `getThreads` -> `Users.findOne(..).fetch().threads`

(ps: there are some missing holes like `addThread`, all the removes or so... should come in later but feel free to add an interface if you feel like it)

step 1- create a mongo.js in connectors folder and implement all the required mongo queries (each wrapped in a function)
step 2 - call/relace these functions in the models

Hope this clarifies a bit?

**Comment by RamyElkest** [comment]
thanks all for your help
